export const LOAD_CURRICULUMS_START = 'LOAD_CURRICULUMS_START';
export const LOAD_CURRICULUMS_SUCCESS = 'LOAD_CURRICULUMS_SUCCESS';
export const LOAD_CURRICULUMS_FAILURE = 'LOAD_CURRICULUMS_FAILURE';

export const DELETE_CURRICULUM_START = 'DELETE_CURRICULUM_START';
export const DELETE_CURRICULUM_SUCCESS = 'DELETE_CURRICULUM_SUCCESS';
export const DELETE_CURRICULUM_FAILURE = 'DELETE_CURRICULUM_FAILURE';
