export const LOAD_CURRICULUMS_START = "LOAD_CURRICULUMS_START";
export const LOAD_CURRICULUMS_SUCCESS = "LOAD_CURRICULUMS_SUCCESS";
export const LOAD_CURRICULUMS_FAILURE = "LOAD_CURRICULUMS_FAILURE";
